version: "3.1"
services:
  moodle:
    image: moodle:latest
    container_name: moodle
    ports:
      - 8080:8080
    environment:
      TZ: America/Sao_Paulo
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: moodle
      POSTGRES_USER: moodleuser
      POSTGRES_PASSWORD: byu2cxk8CEX9amu@teq

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
