version: "3.1"
services:
  moodle:
    image: moodle:latest
    container_name: moodle
    ports:
      - 8080:8080
    environment:
      TZ: America/New_York
      # HTTP_PROXY: http://192.168.237.15:44355
      # Moodle environment variables
      MOODLE_LANG: en
      MOODLE_DB_TYPE: pgsql
      MOODLE_DB_HOST: db
      MOODLE_DB_NAME: moodle
      MOODLE_DB_USER: moodleuser
      MOODLE_DB_PASSWORD: moodlepw
      MOODLE_SITE_FULLNAME: Moodle
      MOODLE_SITE_SHORTNAME: Moodle
      MOODLE_ADMIN_USER: moodle
      MOODLE_ADMIN_PASSWORD: moodle
      MOODLE_ADMIN_EMAIL: admin@localhost.local
      MOODLE_SUPPORT_EMAIL: support@localhost.local
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: moodle
      POSTGRES_USER: moodleuser
      POSTGRES_PASSWORD: moodlepw
