version: "2.1"
services:
  librex:
    image: moodle:latest
    container_name: moodle
    network_mode: bridge
    ports:
      - 8080:8080
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ./tmp/nginx_logs:/var/log/nginx
      - ./tmp/php_logs:/var/log/php7
    restart: unless-stopped
