version: "3.1"
services:
  moodle:
    image: moodle:latest
    container_name: moodle
    ports:
      - 8080:8080
    environment:
      TZ: America/Sao_Paulo
      # Moodle environment variables
      MOODLE_LANG: pt_br
      MOODLE_DB_TYPE: pgsql
      MOODLE_DB_HOST: db
      MOODLE_DB_NAME: moodle
      MOODLE_DB_USER: moodleuser
      MOODLE_DB_PASSWORD: moodlepw
      MOODLE_SITE_FULLNAME: "Codans Oficial"
      MOODLE_SITE_SHORTNAME: Codans
      MOODLE_ADMIN_USER: juniorbotelho
      MOODLE_ADMIN_PASSWORD: nirvana-blew-boddah
      MOODLE_ADMIN_EMAIL: admin@codans.com.br
      MOODLE_SUPPORT_EMAIL: suporte@codans.com.br
    restart: unless-stopped
    volumes:
      - ./tmp/nginx:/var/log/nginx
      - ./tmp/php:/var/log/php7
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: moodle
      POSTGRES_USER: moodleuser
      POSTGRES_PASSWORD: moodlepw
